apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  namespace: nebulodactyl
spec:
  serviceName: mariadb
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:11.4
          env:
            - name: MARIADB_DATABASE
              value: panel
            - name: MARIADB_USER
              value: nebulodactyl
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: MARIADB_PASSWORD
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: MARIADB_ROOT_PASSWORD
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
          readinessProbe:
            exec:
              command: ["mariadb-admin", "status", "--silent"]
            periodSeconds: 10
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 8Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: nebulodactyl
spec:
  selector:
    app: mariadb
  ports:
    - port: 3306
      targetPort: 3306
